#define P3_INDEX 0
#define K3_INDEX 2
#define P2_INDEX 4
#define K2_INDEX 6
#define P1_INDEX 8
#define K1_INDEX 10
#define PLATE_RIGHT_INDEX 12
#define PLATE_DOWNRIGHT_INDEX 13
#define PLATE_DOWN_INDEX 14
#define PLATE_DOWNLEFT_INDEX 15
#define PLATE_LEFT_INDEX 16
#define PLATE_UPLEFT_INDEX 17
#define PLATE_UP_INDEX 18
#define PLATE_UPRIGHT_INDEX 19

#define wiring 14
char* colors[14] = {P1,P2,P3,K1,K2,K3,PLATE_RIGHT,PLATE_DOWNRIGHT,PLATE_DOWN,PLATE_DOWNLEFT,PLATE_LEFT,PLATE_UPLEFT,PLATE_UP,PLATE_UPRIGHT};
int order[14] = {P1_INDEX,P2_INDEX,P3_INDEX,K1_INDEX,K2_INDEX,K3_INDEX,PLATE_RIGHT_INDEX,PLATE_DOWNRIGHT_INDEX,PLATE_DOWN_INDEX,PLATE_DOWNLEFT_INDEX,PLATE_LEFT_INDEX,PLATE_UPLEFT_INDEX,PLATE_UP_INDEX,PLATE_UPRIGHT_INDEX};
int leds[14] = {2,2,2,2,2,2,1,1,1,1,1,1,1,1};
/*
	EOF
*/

/*
#define LEFT_INDEX 0
#define DOWN_INDEX 2
#define RIGHT_INDEX 4
#define UP_INDEX 6
#define K1_INDEX 8
#define P1_INDEX 10
#define P2_INDEX 12
#define K2_INDEX 14
#define K3_INDEX 16
#define P3_INDEX 18
#define P4_INDEX 20
#define K4_INDEX 22

#define wiring 12
char* colors[12] = {LEFT,DOWN,RIGHT,UP,K1,P1,P2,K2,K3,P3,P4,K4};
int order[12] = {LEFT_INDEX,DOWN_INDEX,RIGHT_INDEX,UP_INDEX,K1_INDEX,P1_INDEX,P2_INDEX,K2_INDEX,K3_INDEX,P3_INDEX,P4_INDEX,K4_INDEX};
int leds[12] = {2,2,2,2,2,2,2,2,2,2,2,2};
*/
/*
	EOF
*/