#define P3_INDEX 0
#define K3_INDEX 2
#define P2_INDEX 4
#define K2_INDEX 6
#define PLATE_RIGHT_INDEX 8
#define PLATE_DOWNRIGHT_INDEX 9
#define PLATE_DOWN_INDEX 10
#define PLATE_DOWNLEFT_INDEX 11
#define PLATE_LEFT_INDEX 12
#define PLATE_UPLEFT_INDEX 13
#define PLATE_UP_INDEX 14
#define PLATE_UPRIGHT_INDEX 15

#define wiring 12
char* colors[12] = {P3,K3,P2,K2,PLATE_RIGHT,PLATE_DOWNRIGHT,PLATE_DOWN,PLATE_DOWNLEFT,PLATE_LEFT,PLATE_UPLEFT,PLATE_UP,PLATE_UPRIGHT};
int order[12] = {P3_INDEX,K3_INDEX,P2_INDEX,K2_INDEX,PLATE_RIGHT_INDEX,PLATE_DOWNRIGHT_INDEX,PLATE_DOWN_INDEX,PLATE_DOWNLEFT_INDEX,PLATE_LEFT_INDEX,PLATE_UPLEFT_INDEX,PLATE_UP_INDEX,PLATE_UPRIGHT_INDEX};
int leds[12] = {2,2,2,2,1,1,1,1,1,1,1,1};
/*
	EOF
*/