
#define PLATE_RIGHT_INDEX 0
#define PLATE_DOWNRIGHT_INDEX 1
#define PLATE_DOWN_INDEX 2
#define PLATE_DOWNLEFT_INDEX 3
#define PLATE_LEFT_INDEX 4
#define PLATE_UPLEFT_INDEX 5
#define PLATE_UP_INDEX 6
#define PLATE_UPRIGHT_INDEX 7
#define P1_INDEX 8
#define P2_INDEX 10
#define P3_INDEX 12
#define K3_INDEX 14
#define K2_INDEX 16
#define K1_INDEX 18

#define wiring 14
char* colors[14] = {PLATE_RIGHT,PLATE_DOWNRIGHT,PLATE_DOWN,PLATE_DOWNLEFT,PLATE_LEFT,PLATE_UPLEFT,PLATE_UP,PLATE_UPRIGHT,P1,P2,P3,K3,K2,K1};
int order[14] = {PLATE_RIGHT_INDEX,PLATE_DOWNRIGHT_INDEX,PLATE_DOWN_INDEX,PLATE_DOWNLEFT_INDEX,PLATE_LEFT_INDEX,PLATE_UPLEFT_INDEX,PLATE_UP_INDEX,PLATE_UPRIGHT_INDEX,P1_INDEX,P2_INDEX,P3_INDEX,K3_INDEX,K2_INDEX,K1_INDEX};
int leds[14] = {1,1,1,1,1,1,1,1,2,2,2,2,2,2};
/*
	EOF
*/

/*
#define PLATE_RIGHT_INDEX 0
#define PLATE_DOWNRIGHT_INDEX 1
#define PLATE_DOWN_INDEX 2
#define PLATE_DOWNLEFT_INDEX 3
#define PLATE_LEFT_INDEX 4
#define PLATE_UPLEFT_INDEX 5
#define PLATE_UP_INDEX 6
#define PLATE_UPRIGHT_INDEX 7

#define wiring 8
char* colors[8] = {PLATE_RIGHT,PLATE_DOWNRIGHT,PLATE_DOWN,PLATE_DOWNLEFT,PLATE_LEFT,PLATE_UPLEFT,PLATE_UP,PLATE_UPRIGHT};
int order[8] = {PLATE_RIGHT_INDEX,PLATE_DOWNRIGHT_INDEX,PLATE_DOWN_INDEX,PLATE_DOWNLEFT_INDEX,PLATE_LEFT_INDEX,PLATE_UPLEFT_INDEX,PLATE_UP_INDEX,PLATE_UPRIGHT_INDEX};
int leds[8] = {1,1,1,1,1,1,1,1};
*/